"""add_stratum_fields

Revision ID: 397655860e44
Revises: 0002_initial_tables
Create Date: 2026-05-19 15:29:33.146799

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '397655860e44'
down_revision: str | Sequence[str] | None = '0002_initial_tables'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdf_extraction_jobs', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'awaiting_review', 'approved', 'failed', name='extraction_job_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pdf_templates', 'box_definitions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('project_members', 'role',
               existing_type=postgresql.ENUM('owner', 'editor', 'viewer', name='project_member_role'),
               server_default=None,
               existing_nullable=False)
    op.add_column('strata', sa.Column('n_value', sa.Float(), nullable=True))
    op.add_column('strata', sa.Column('uscs_code', sa.String(length=20), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('designer', 'expert', 'reviewer', 'admin', name='user_role'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('designer', 'expert', 'reviewer', 'admin', name='user_role'),
               server_default=sa.text("'designer'::user_role"),
               existing_nullable=False)
    op.drop_column('strata', 'uscs_code')
    op.drop_column('strata', 'n_value')
    op.alter_column('project_members', 'role',
               existing_type=postgresql.ENUM('owner', 'editor', 'viewer', name='project_member_role'),
               server_default=sa.text("'viewer'::project_member_role"),
               existing_nullable=False)
    op.alter_column('pdf_templates', 'box_definitions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=False)
    op.alter_column('pdf_extraction_jobs', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'awaiting_review', 'approved', 'failed', name='extraction_job_status'),
               server_default=sa.text("'pending'::extraction_job_status"),
               existing_nullable=False)
    # ### end Alembic commands ###
